const MONEY_MESSAGES = {
  ru: {
    common: {
      money: 'Деньги',
      loading: 'Загрузка...',
      retry: 'Повторить',
      create: 'Создать',
      save: 'Сохранить',
      saving: 'Сохраняем...',
      cancel: 'Отмена',
      close: 'Закрыть',
      edit: 'Редактировать',
      delete: 'Удалить',
      deleting: 'Удаляем...',
      back: 'Назад',
      open: 'Открыть',
      all: 'Все',
      amount: 'Сумма',
      currency: 'Валюта',
      status: 'Статус',
      method: 'Метод',
      label: 'Название',
      createdAt: 'Создано',
      updatedAt: 'Обновлено',
      approvedAt: 'Подтверждено',
      completedAt: 'Выполнено',
      rejectedAt: 'Отклонено',
      cancelledAt: 'Отменено',
      requestedAmount: 'Запрошенная сумма',
      actualPayoutAmount: 'Фактическая сумма выплаты',
      requisites: 'Реквизиты',
      details: 'Детали',
      summary: 'Сводка',
      notAvailable: '—',
      noDataTitle: 'Пока пусто',
      unknown: 'Неизвестно',
      filters: 'Фильтры',
      clearFilters: 'Сбросить фильтры',
      previousPage: 'Назад',
      nextPage: 'Дальше',
      page: 'Страница',
      of: 'из',
      active: 'Активно',
      inactive: 'Неактивно',
      default: 'По умолчанию',
      makeDefault: 'Сделать основными',
      description: 'Описание',
      continue: 'Продолжить',
      submit: 'Отправить',
      creating: 'Создаем...',
      requestId: 'ID заявки',
      note: 'Примечание',
      profile: 'Профиль',
      optional: 'Необязательно',
      operation: 'Операция',
      balance: 'Баланс',
      available: 'Доступно',
      reserved: 'В резерве',
      deposit: 'Пополнить',
      withdraw: 'Вывести',
    },
    nav: {
      transactions: 'История операций',
      payoutProfiles: 'Сохраненные реквизиты',
      deposit: 'Пополнение',
      withdraw: 'Вывод',
    },
    wallet: {
      eyebrow: 'Wallet',
      title: 'Кошелек',
      subtitle:
        'Все балансы, быстрые действия по пополнению и выводу, плюс компактный блок последних операций.',
      showZero: 'Показать нулевые',
      hideZero: 'Скрыть нулевые',
      showAll: 'Показать все валюты',
      activeCurrencies: 'Активные валюты',
      hiddenCurrencies: 'Скрыто нулевых',
      totalCurrencies: 'Всего валют',
      headerCurrencyTitle: 'Валюта в шапке',
      headerCurrencyHint:
        'Выбранная валюта влияет на balance control в header. Переключение сохраняется глобально.',
      setInHeader: 'Показывать в шапке',
      selectedInHeader: 'Уже в шапке',
      recentTitle: 'Последние операции',
      recentSubtitle: 'Показываем последние 5 операций без ухода со страницы кошелька.',
      recentEmpty: 'Здесь появятся ваши последние начисления и траты.',
      openHistory: 'Открыть полную историю',
      loadError: 'Не удалось загрузить кошелек.',
      zeroHiddenTitle: 'Нулевые балансы скрыты',
      zeroHiddenText:
        'Все доступные валюты есть в системе, но сейчас видимы только ненулевые балансы.',
      emptyTitle: 'Кошельки пока пусты',
      emptyText: 'Баланс появится после депозита, подтвержденных сделок или внутренних начислений.',
      cardActions: 'Действия по валюте',
    },
    transactions: {
      eyebrow: 'Ledger',
      title: 'История операций',
      subtitle:
        'Фильтруйте движения по валюте и типу, просматривайте сумму, дату и описание операции.',
      currencyFilter: 'Фильтр по валюте',
      typeFilter: 'Фильтр по типу',
      emptyTitle: 'Операций не найдено',
      emptyText: 'Попробуйте изменить фильтры или вернитесь позже.',
      loadError: 'Не удалось загрузить историю операций.',
      typeUnknown: 'Тип не указан',
      descriptionEmpty: 'Без описания',
      reference: 'Референс',
    },
    deposits: {
      title: 'Пополнение',
      subtitle:
        'Выберите валюту, способ пополнения и сумму. После создания заявки вы сразу попадете на страницу деталей.',
      chooseCurrency: 'Выберите валюту',
      chooseMethod: 'Выберите метод',
      amountHint: 'Сумма должна быть больше нуля.',
      selectedWallet: 'Кошелек для пополнения',
      requestsTitle: 'Заявки на пополнение',
      requestsSubtitle:
        'Все пользовательские заявки на пополнение с переходом к детальной карточке и статусам.',
      detailsSubtitle:
        'Используем snapshot заявки: статус, метод и реквизиты берутся из backend-ответа по самой заявке.',
      timeline: 'Хронология',
      noTimeline: 'События появятся по мере движения заявки.',
      paymentDetailsEmpty: 'Реквизиты еще не выданы оператором.',
      newDeposit: 'Новое пополнение',
      openList: 'К заявкам',
      statusNoteTitle: 'Что делать дальше',
    },
    withdrawals: {
      title: 'Вывод',
      subtitle:
        'Выберите валюту, метод вывода, сохраненный профиль или новые реквизиты, затем создайте заявку.',
      requestsTitle: 'Заявки на вывод',
      requestsSubtitle:
        'Список заявок на вывод с переходом к деталям, статусу обработки и доступным действиям.',
      detailsSubtitle:
        'Детальная карточка показывает snapshot реквизитов, сумму выплаты и комментарии оператора.',
      selectCurrency: 'Валюта вывода',
      selectMethod: 'Метод вывода',
      selectProfile: 'Сохраненный профиль',
      enterNew: 'Ввести новые реквизиты',
      useSaved: 'Использовать сохраненные',
      saveNewProfile: 'Сохранить эти реквизиты',
      saveNewProfileHint:
        'Новый payout profile будет доступен на отдельной странице и в следующих выводах.',
      minAmount: 'Минимальная сумма',
      methodNote: 'Комментарий по методу',
      roundingInfo: 'Правила округления',
      summaryTitle: 'Итог перед отправкой',
      summaryHint:
        'Сейчас фиксируем запрошенную сумму. Если фактическая сумма выплаты определяется позже, это уточнит оператор.',
      actualPayoutPending:
        'Фактическая сумма выплаты может быть уточнена оператором после обработки заявки.',
      createError: 'Не удалось создать заявку на вывод.',
      loadError: 'Не удалось загрузить данные для вывода.',
      listError: 'Не удалось загрузить заявки на вывод.',
      detailsError: 'Не удалось загрузить заявку на вывод.',
      cancelError: 'Не удалось отменить заявку на вывод.',
      cancelAction: 'Отменить заявку',
      newWithdrawal: 'Новый вывод',
      amountPlaceholder: 'Введите сумму вывода',
      amountRequired: 'Введите сумму вывода.',
      amountInvalid: 'Укажите корректную сумму вывода.',
      amountTooSmall: 'Сумма меньше минимально допустимой для выбранного метода.',
      methodRequired: 'Выберите метод вывода.',
      currencyRequired: 'Выберите валюту.',
      profileRequired: 'Выберите сохраненный профиль или переключитесь на новые реквизиты.',
      requisitesRequired: 'Заполните реквизиты для выбранного метода.',
      labelRequired: 'Укажите название для сохранения реквизитов.',
      savedProfilesEmpty:
        'Для выбранной валюты и метода нет сохраненных профилей. Можно сразу ввести новые реквизиты.',
      detailComment: 'Комментарий оператора',
      detailReason: 'Причина отклонения',
      payoutRequisites: 'Снимок реквизитов',
      payoutRequisitesEmpty: 'Снимок реквизитов пока не получен.',
      timeline: 'Этапы обработки',
      noTimeline: 'События обработки пока не зафиксированы.',
      emptyTitle: 'Заявок на вывод пока нет',
      emptyText: 'Создайте первую заявку на вывод со страницы вывода.',
    },
    payoutProfiles: {
      title: 'Сохраненные реквизиты',
      subtitle:
        'Управляйте payout profiles: создавайте, редактируйте, удаляйте и назначайте профиль по умолчанию.',
      createTitle: 'Новый профиль',
      editTitle: 'Редактирование профиля',
      formSubtitle:
        'Профили группируются по методу. При создании вывода профиль по умолчанию подставляется автоматически.',
      listTitle: 'Ваши реквизиты',
      emptyTitle: 'Профилей пока нет',
      emptyText: 'Сохраните реквизиты здесь или отметьте их во время создания вывода.',
      loadError: 'Не удалось загрузить payout profiles.',
      saveError: 'Не удалось сохранить payout profile.',
      deleteError: 'Не удалось удалить payout profile.',
      defaultError: 'Не удалось назначить профиль по умолчанию.',
      deleteConfirm: 'Удалить этот профиль реквизитов?',
      deleteAction: 'Удалить профиль',
      defaultBadge: 'Основной',
      groupFallback: 'Без метода',
      createAction: 'Добавить реквизиты',
      resetForm: 'Очистить форму',
      methodHelp:
        'Если метод зависит от валюты, сначала выберите валюту, затем backend загрузит доступные withdrawal methods.',
      setDefaultHint:
        'Профиль по умолчанию автоматически подставляется в форме вывода для той же валюты и метода.',
    },
    statuses: {
      withdrawal: {
        OPEN: 'Открыта',
        CREATED: 'Создана',
        PENDING: 'Ожидает обработки',
        PROCESSING: 'В обработке',
        IN_PROGRESS: 'В обработке',
        UNDER_REVIEW: 'На проверке',
        COMPLETED: 'Выполнена',
        DONE: 'Выполнена',
        PAID: 'Выплачена',
        REJECTED: 'Отклонена',
        FAILED: 'Ошибка',
        CANCELLED: 'Отменена',
        EXPIRED: 'Истекла',
      },
    },
    methodFields: {
      currencyLabel: 'Валюта',
      currencyPlaceholder: 'Выберите валюту',
      methodLabel: 'Метод',
      methodPlaceholder: 'Выберите метод',
      profileLabel: 'Название профиля',
      profilePlaceholder: 'Например: SBP Сбер, основной USDT кошелек',
      phoneLabel: 'Номер телефона',
      phonePlaceholder: '+7 999 123-45-67',
      bankLabel: 'Банк',
      bankPlaceholder: 'Например: Сбербанк',
      recipientLabel: 'Получатель',
      recipientPlaceholder: 'Имя получателя',
      addressLabel: 'Адрес кошелька',
      addressPlaceholder: 'Введите адрес',
      networkLabel: 'Сеть',
      networkPlaceholder: 'Выберите сеть или введите ее вручную',
      networkCustomPlaceholder: 'Например: TRC20',
      uidLabel: 'UID',
      uidPlaceholder: 'Введите UID',
      genericLabel: 'Реквизиты',
      genericPlaceholder: 'Введите реквизиты',
      phoneError: 'Укажите корректный номер телефона.',
      bankError: 'Укажите банк.',
      recipientError: 'Укажите имя получателя.',
      addressError: 'Укажите адрес.',
      networkError: 'Укажите сеть.',
      uidError: 'Укажите UID.',
      genericError: 'Заполните реквизиты.',
    },
  },
  en: {
    common: {
      money: 'Money',
      loading: 'Loading...',
      retry: 'Retry',
      create: 'Create',
      save: 'Save',
      saving: 'Saving...',
      cancel: 'Cancel',
      close: 'Close',
      edit: 'Edit',
      delete: 'Delete',
      deleting: 'Deleting...',
      back: 'Back',
      open: 'Open',
      all: 'All',
      amount: 'Amount',
      currency: 'Currency',
      status: 'Status',
      method: 'Method',
      label: 'Label',
      createdAt: 'Created',
      updatedAt: 'Updated',
      approvedAt: 'Approved',
      completedAt: 'Completed',
      rejectedAt: 'Rejected',
      cancelledAt: 'Cancelled',
      requestedAmount: 'Requested amount',
      actualPayoutAmount: 'Actual payout amount',
      requisites: 'Requisites',
      details: 'Details',
      summary: 'Summary',
      notAvailable: '\u2014',
      noDataTitle: 'Nothing here yet',
      unknown: 'Unknown',
      filters: 'Filters',
      clearFilters: 'Clear filters',
      previousPage: 'Previous',
      nextPage: 'Next',
      page: 'Page',
      of: 'of',
      active: 'Active',
      inactive: 'Inactive',
      default: 'Default',
      makeDefault: 'Set default',
      description: 'Description',
      continue: 'Continue',
      submit: 'Submit',
      creating: 'Creating...',
      requestId: 'Request ID',
      note: 'Note',
      profile: 'Profile',
      optional: 'Optional',
      operation: 'Operation',
      balance: 'Balance',
      available: 'Available',
      reserved: 'Reserved',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
    },
    nav: {
      transactions: 'Transactions',
      payoutProfiles: 'Saved requisites',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
    },
    wallet: {
      eyebrow: 'Wallet',
      title: 'Wallet',
      subtitle:
        'All balances, quick deposit and withdrawal actions, plus a compact preview of recent operations.',
      showZero: 'Show zero balances',
      hideZero: 'Hide zero balances',
      showAll: 'Show all currencies',
      activeCurrencies: 'Active currencies',
      hiddenCurrencies: 'Hidden zero balances',
      totalCurrencies: 'Total currencies',
      headerCurrencyTitle: 'Header currency',
      headerCurrencyHint:
        'The selected currency drives the header balance control. The choice is kept globally.',
      setInHeader: 'Show in header',
      selectedInHeader: 'Already in header',
      recentTitle: 'Recent transactions',
      recentSubtitle: 'Shows the latest 5 operations without leaving the wallet page.',
      recentEmpty: 'Your latest credits and spending will appear here.',
      openHistory: 'Open full history',
      loadError: "Couldn't load the wallet.",
      zeroHiddenTitle: 'Zero balances are hidden',
      zeroHiddenText:
        'All available currencies still exist in the system, but only non-zero balances are currently visible.',
      emptyTitle: 'Wallets are empty',
      emptyText: 'Balances will appear after deposits, confirmed trades, or internal credits.',
      cardActions: 'Currency actions',
    },
    transactions: {
      eyebrow: 'Ledger',
      title: 'Transaction history',
      subtitle:
        'Filter movements by currency and type, then review amount, date, and operation details.',
      currencyFilter: 'Currency filter',
      typeFilter: 'Type filter',
      emptyTitle: 'No transactions found',
      emptyText: 'Try changing filters or come back later.',
      loadError: "Couldn't load transaction history.",
      typeUnknown: 'Type not provided',
      descriptionEmpty: 'No description',
      reference: 'Reference',
    },
    deposits: {
      title: 'Deposit',
      subtitle:
        'Choose a currency, deposit method, and amount. After the request is created you will be redirected to its details page.',
      chooseCurrency: 'Choose currency',
      chooseMethod: 'Choose method',
      amountHint: 'The amount must be greater than zero.',
      selectedWallet: 'Wallet to top up',
      requestsTitle: 'Deposit requests',
      requestsSubtitle:
        'All user deposit requests with a direct path to the details page and current statuses.',
      detailsSubtitle:
        'We rely on the request snapshot from backend: status, method, and requisites come from the request itself.',
      timeline: 'Timeline',
      noTimeline: 'Events will appear as the request moves forward.',
      paymentDetailsEmpty: 'Payment details have not been issued yet.',
      newDeposit: 'New deposit',
      openList: 'Back to requests',
      statusNoteTitle: 'What to do next',
    },
    withdrawals: {
      title: 'Withdraw',
      subtitle:
        'Choose currency, withdrawal method, a saved profile or new requisites, then create the request.',
      requestsTitle: 'Withdrawal requests',
      requestsSubtitle:
        'A list of withdrawal requests with drill-down into details, processing status, and available actions.',
      detailsSubtitle:
        'The request page shows requisites snapshot, payout amount, and operator comments.',
      selectCurrency: 'Withdrawal currency',
      selectMethod: 'Withdrawal method',
      selectProfile: 'Saved profile',
      enterNew: 'Enter new requisites',
      useSaved: 'Use saved profile',
      saveNewProfile: 'Save these requisites',
      saveNewProfileHint:
        'The new payout profile will be available on the dedicated page and during future withdrawals.',
      minAmount: 'Minimum amount',
      methodNote: 'Method note',
      roundingInfo: 'Rounding info',
      summaryTitle: 'Submission summary',
      summaryHint:
        'The UI confirms the requested amount now. If the actual payout amount is determined later, the operator will уточнить it.',
      actualPayoutPending:
        'The actual payout amount may be уточнена by the operator after the request is processed.',
      createError: "Couldn't create the withdrawal request.",
      loadError: "Couldn't load withdrawal data.",
      listError: "Couldn't load withdrawal requests.",
      detailsError: "Couldn't load the withdrawal request.",
      cancelError: "Couldn't cancel the withdrawal request.",
      cancelAction: 'Cancel request',
      newWithdrawal: 'New withdrawal',
      amountPlaceholder: 'Enter withdrawal amount',
      amountRequired: 'Enter the withdrawal amount.',
      amountInvalid: 'Enter a valid withdrawal amount.',
      amountTooSmall: 'The amount is below the minimum for the selected method.',
      methodRequired: 'Choose a withdrawal method.',
      currencyRequired: 'Choose a currency.',
      profileRequired: 'Choose a saved profile or switch to new requisites.',
      requisitesRequired: 'Fill in requisites for the selected method.',
      labelRequired: 'Provide a label if you want to save the requisites.',
      savedProfilesEmpty:
        'There are no saved profiles for the selected currency and method. You can enter new requisites right away.',
      detailComment: 'Operator comment',
      detailReason: 'Rejection reason',
      payoutRequisites: 'Requisites snapshot',
      payoutRequisitesEmpty: 'The requisites snapshot is not available yet.',
      timeline: 'Processing timeline',
      noTimeline: 'No processing events are available yet.',
      emptyTitle: 'No withdrawal requests yet',
      emptyText: 'Create your first withdrawal from the withdrawal page.',
    },
    payoutProfiles: {
      title: 'Saved requisites',
      subtitle:
        'Manage payout profiles: create, edit, delete, and assign the default one for future withdrawals.',
      createTitle: 'New profile',
      editTitle: 'Edit profile',
      formSubtitle:
        'Profiles are grouped by method. The default profile is preselected automatically in the withdrawal form.',
      listTitle: 'Your requisites',
      emptyTitle: 'No profiles yet',
      emptyText: 'Save requisites here or mark them during withdrawal creation.',
      loadError: "Couldn't load payout profiles.",
      saveError: "Couldn't save the payout profile.",
      deleteError: "Couldn't delete the payout profile.",
      defaultError: "Couldn't set the default payout profile.",
      deleteConfirm: 'Delete this payout profile?',
      deleteAction: 'Delete profile',
      defaultBadge: 'Default',
      groupFallback: 'No method',
      createAction: 'Add requisites',
      resetForm: 'Reset form',
      methodHelp:
        'If the method depends on currency, choose currency first and backend will return the available withdrawal methods.',
      setDefaultHint:
        'The default profile is automatically selected in the withdrawal form for the same currency and method.',
    },
    statuses: {
      withdrawal: {
        OPEN: 'Open',
        CREATED: 'Created',
        PENDING: 'Pending',
        PROCESSING: 'Processing',
        IN_PROGRESS: 'In progress',
        UNDER_REVIEW: 'Under review',
        COMPLETED: 'Completed',
        DONE: 'Completed',
        PAID: 'Paid',
        REJECTED: 'Rejected',
        FAILED: 'Failed',
        CANCELLED: 'Cancelled',
        EXPIRED: 'Expired',
      },
    },
    methodFields: {
      currencyLabel: 'Currency',
      currencyPlaceholder: 'Select currency',
      methodLabel: 'Method',
      methodPlaceholder: 'Select method',
      profileLabel: 'Profile label',
      profilePlaceholder: 'For example: Main SBP, Primary USDT wallet',
      phoneLabel: 'Phone number',
      phonePlaceholder: '+7 999 123-45-67',
      bankLabel: 'Bank name',
      bankPlaceholder: 'For example: Sberbank',
      recipientLabel: 'Recipient name',
      recipientPlaceholder: 'Recipient name',
      addressLabel: 'Wallet address',
      addressPlaceholder: 'Enter the address',
      networkLabel: 'Network',
      networkPlaceholder: 'Select network or enter it manually',
      networkCustomPlaceholder: 'For example: TRC20',
      uidLabel: 'UID',
      uidPlaceholder: 'Enter UID',
      genericLabel: 'Requisites',
      genericPlaceholder: 'Enter requisites',
      phoneError: 'Enter a valid phone number.',
      bankError: 'Enter the bank name.',
      recipientError: 'Enter the recipient name.',
      addressError: 'Enter the address.',
      networkError: 'Enter the network.',
      uidError: 'Enter UID.',
      genericError: 'Fill in the requisites.',
    },
  },
}

export function getMoneyCopy(language = 'ru') {
  return MONEY_MESSAGES[language] || MONEY_MESSAGES.ru
}
