const MARKET_MESSAGES = {
  ru: {
    eyebrow: 'Двусторонний рынок',
    title: 'P2P рынок игровых ценностей',
    subtitle:
      'Купить у продавцов или продать в заявки на скупку. Цены показаны в выбранной валюте.',
    unsupportedCategoryTitle: 'Рынок этой категории пока недоступен',
    unsupportedCategoryText:
      'Публичный listing сейчас поддерживает только валюту. Предметы, услуги и наборы останутся видимыми как направления продукта, но офферы по ним здесь пока не загружаются.',
    common: {
      loading: 'Загрузка...',
      retry: 'Повторить',
      reset: 'Сбросить',
      noValue: 'Не указано',
      fallbackTitle: 'Валютный оффер',
      close: 'Закрыть',
      results: 'офферов',
      page: 'Страница',
      of: 'из',
      allGames: 'Игры недоступны',
      noCategories: 'Категории недоступны',
      filtersPending: 'Загружаем фильтры рынка...',
      filtersUnavailable: 'Выберите игру и доступную категорию, чтобы увидеть офферы.',
      comingSoon: 'Скоро',
      live: 'Доступно',
      apply: 'Применить',
    },
    toolbar: {
      intent: 'Сценарий',
      intentPrompt: 'Я хочу',
      buyCode: 'Купить',
      sellCode: 'Продать',
      buyHint: 'Показаны sell-офферы других игроков.',
      sellHint: 'Показаны buy-офферы на скупку.',
      game: 'Игра',
      selectGame: 'Выберите игру',
      gamesLoading: 'Загружаем игры...',
      gameSearch: 'Найти игру',
      gamePickerEmpty: 'Игр по этому запросу нет.',
      category: 'Категория',
      selectCategory: 'Выберите категорию',
      viewerCurrency: 'Валюта отображения',
      viewerCurrencyLoading: 'Загружаем валюты...',
      viewerCurrencyFallback: 'Показываем поддержанные валюты рынка.',
      viewerCurrencyHelp:
        'Цены офферов запрашиваются и показываются в этой валюте. Смена валюты обновит список без ручного пересчета.',
      sort: 'Сортировка',
      filtersTitle: 'Фильтры',
      filtersSubtitle: 'Фильтры ниже соответствуют схеме выбранной игры и поддерживаются API.',
      commandTitle: 'Настройка сделки',
      commandSubtitle:
        'Выберите, покупаете вы у продавцов или продаете в скупку, затем задайте игру и валюту просмотра.',
      bannerTitle: 'Рабочая зона рынка',
      bannerText:
        'Валютные офферы доступны сейчас. Остальные категории показаны честно как неподключенные к listing.',
      mobileFilters: 'Фильтры',
    },
    category: {
      currencyDescription: 'Публичные валютные офферы доступны сейчас.',
      soonDescription: 'Listing для этой категории пока не поддержан.',
      noLiveCategory:
        'Для выбранной игры пока нет подключенной валютной категории.',
    },
    intent: {
      buy: 'Купить',
      sell: 'Продать',
    },
    side: {
      buy: 'Buy-оффер',
      sell: 'Sell-оффер',
    },
    actions: {
      buy: 'Купить',
      sell: 'Продать',
    },
    sort: {
      price_asc: 'Сначала дешевле',
      price_desc: 'Сначала дороже',
    },
    list: {
      title: 'Офферы рынка',
      subtitleBuy: 'Вы покупаете у продавцов. В списке показаны доступные sell-офферы.',
      subtitleSell: 'Вы продаете в скупку. В списке показаны buy-офферы других игроков.',
      columns: {
        trader: 'Трейдер',
        offer: 'Оффер',
        price: 'Цена',
        trade: 'Количество и лимиты',
        delivery: 'Передача',
        action: 'Действие',
      },
      owner: 'Трейдер',
      quantity: 'Доступно',
      limits: 'Лимиты',
      step: 'Шаг',
      context: 'Контекст',
      attributes: 'Атрибуты',
      delivery: 'Передача',
      published: 'Опубликован',
      rate: 'Курс',
      unitPrice: 'Цена за единицу',
      loadingRefresh: 'Обновляем офферы...',
      noOffersTitle: 'Офферов по этим условиям нет',
      noOffersText:
        'Смените сценарий, тип валюты или контекст. Мы показываем только реальные публичные офферы, которые вернул API.',
      errorTitle: 'Не удалось загрузить офферы рынка.',
      previous: 'Назад',
      next: 'Далее',
      showing: 'Показано',
      setupTitle: 'Настройте рынок',
      setupText: 'Выберите игру, валюту и доступную категорию, чтобы открыть список офферов.',
    },
    modal: {
      title: 'Детали оффера',
      descriptionFallback: 'Описание не указано.',
      tradeTermsFallback: 'Дополнительные условия сделки не указаны.',
      sectionContext: 'Контекст сделки',
      sectionAttributes: 'Атрибуты',
      sectionDelivery: 'Способы передачи',
      sectionDescription: 'Описание',
      sectionTerms: 'Условия сделки',
      sectionOrder: 'Расчет сделки',
      quantity: 'Доступное количество',
      minTradeQuantity: 'Минимум за сделку',
      maxTradeQuantity: 'Максимум за сделку',
      quantityStep: 'Шаг количества',
      publishedAt: 'Опубликован',
      quoteTimer: 'Quote действует',
      quoteExpired: 'Quote истек. Обновляем расчет.',
      quoteRefreshing: 'Обновляем расчет...',
      refreshButton: 'Обновить quote',
      quantityInputLabel: 'Количество',
      quantityHintsPrefix: 'Ограничения',
      quantityHintAvailable: 'доступно',
      quantityHintMin: 'мин.',
      quantityHintMax: 'макс.',
      quantityHintStep: 'шаг',
      totalLabel: 'Итого',
      unitPriceLabel: 'Цена за единицу',
      unavailable:
        'Оффер сейчас недоступен. Закройте окно и выберите другой оффер.',
      priceChanged:
        'Цена изменилась после обновления курса. Проверьте итоговую сумму.',
      offerUpdated:
        'Оффер обновился. Проверьте условия перед созданием заказа.',
      submitPending: 'Создаем заказ...',
      submitReady: 'Проверьте количество и создайте заказ.',
      submitExpired: 'Quote истек. Дождитесь обновления расчета.',
      invalidQuantity: 'Введите корректное количество.',
      positiveQuantity: 'Количество должно быть больше нуля.',
      minQuantity: 'Количество должно быть не меньше {value}.',
      maxQuantity: 'Количество должно быть не больше {value}.',
      availableQuantity: 'Количество не может превышать доступный остаток ({value}).',
      stepQuantity: 'Количество должно соответствовать шагу {value}.',
      loading: 'Загружаем детали оффера...',
      error: 'Не удалось загрузить детали оффера.',
    },
    errors: {
      games: 'Не удалось загрузить игры.',
      currencies: 'Не удалось загрузить список валют.',
      categories: 'Не удалось загрузить категории для выбранной игры.',
      schema: 'Не удалось загрузить схему рынка.',
      offers: 'Не удалось загрузить офферы рынка.',
      offerDetails: 'Не удалось загрузить детали оффера.',
      quoteCreate: 'Не удалось создать quote для оффера.',
      quoteRefresh: 'Не удалось обновить quote.',
      orderCreate: 'Не удалось создать заказ.',
      currencyUnsupported:
        'Валюта {code} недоступна для текущего рынка. Показали цены в {fallback}.',
    },
  },
  en: {
    eyebrow: 'Two-sided market',
    title: 'Gaming P2P market',
    subtitle:
      'Buy from sellers or sell into buy offers. Prices are shown in your selected currency.',
    unsupportedCategoryTitle: 'This category is not listed yet',
    unsupportedCategoryText:
      'Public listing currently supports currency only. Items, services, and packs stay visible as product directions, but offers for them are not loaded here yet.',
    common: {
      loading: 'Loading...',
      retry: 'Retry',
      reset: 'Reset',
      noValue: 'Not specified',
      fallbackTitle: 'Currency offer',
      close: 'Close',
      results: 'offers',
      page: 'Page',
      of: 'of',
      allGames: 'No games available',
      noCategories: 'No categories available',
      filtersPending: 'Loading market filters...',
      filtersUnavailable: 'Choose a game and a live category to see offers.',
      comingSoon: 'Soon',
      live: 'Live',
      apply: 'Apply',
    },
    toolbar: {
      intent: 'Intent',
      intentPrompt: 'I want to',
      buyCode: 'Buy',
      sellCode: 'Sell',
      buyHint: 'Shows sell offers from other players.',
      sellHint: 'Shows buy offers posted by other players.',
      game: 'Game',
      selectGame: 'Select game',
      gamesLoading: 'Loading games...',
      gameSearch: 'Search game',
      gamePickerEmpty: 'No games found for this query.',
      category: 'Category',
      selectCategory: 'Select category',
      viewerCurrency: 'Display currency',
      viewerCurrencyLoading: 'Loading currencies...',
      viewerCurrencyFallback: 'Showing market-supported currencies.',
      viewerCurrencyHelp:
        'Offer prices are requested and displayed in this currency. Changing it refreshes the list without manual conversion.',
      sort: 'Sort',
      filtersTitle: 'Filters',
      filtersSubtitle: 'These filters come from the selected game schema and are supported by the API.',
      commandTitle: 'Trade setup',
      commandSubtitle:
        'Choose whether you buy from sellers or sell into buy offers, then set game and display currency.',
      bannerTitle: 'Market workspace',
      bannerText:
        'Currency offers are live now. Other categories are shown honestly as not connected to public listing yet.',
      mobileFilters: 'Filters',
    },
    category: {
      currencyDescription: 'Public currency offers are available now.',
      soonDescription: 'Listing for this category is not supported yet.',
      noLiveCategory:
        'The selected game does not have a connected currency category yet.',
    },
    intent: {
      buy: 'Buy',
      sell: 'Sell',
    },
    side: {
      buy: 'Buy offer',
      sell: 'Sell offer',
    },
    actions: {
      buy: 'Buy',
      sell: 'Sell',
    },
    sort: {
      price_asc: 'Lowest price first',
      price_desc: 'Highest price first',
    },
    list: {
      title: 'Market offers',
      subtitleBuy: 'You are buying from sellers. The list shows available sell offers.',
      subtitleSell: 'You are selling into buy offers. The list shows buy offers from other players.',
      columns: {
        trader: 'Trader',
        offer: 'Offer',
        price: 'Price',
        trade: 'Quantity and limits',
        delivery: 'Delivery',
        action: 'Action',
      },
      owner: 'Trader',
      quantity: 'Available',
      limits: 'Limits',
      step: 'Step',
      context: 'Context',
      attributes: 'Attributes',
      delivery: 'Delivery',
      published: 'Published',
      rate: 'Rate',
      unitPrice: 'Unit price',
      loadingRefresh: 'Refreshing offers...',
      noOffersTitle: 'No offers for these conditions',
      noOffersText:
        'Try another intent, currency type, or context. We only show real public offers returned by the API.',
      errorTitle: "Couldn't load market offers.",
      previous: 'Previous',
      next: 'Next',
      showing: 'Showing',
      setupTitle: 'Set up the market',
      setupText: 'Choose a game, display currency, and live category to open the offer list.',
    },
    modal: {
      title: 'Offer details',
      descriptionFallback: 'No description provided.',
      tradeTermsFallback: 'No special trade terms provided.',
      sectionContext: 'Trade context',
      sectionAttributes: 'Attributes',
      sectionDelivery: 'Delivery methods',
      sectionDescription: 'Description',
      sectionTerms: 'Trade terms',
      sectionOrder: 'Deal calculation',
      quantity: 'Available quantity',
      minTradeQuantity: 'Minimum trade',
      maxTradeQuantity: 'Maximum trade',
      quantityStep: 'Quantity step',
      publishedAt: 'Published',
      quoteTimer: 'Quote expires in',
      quoteExpired: 'Quote expired. Refreshing calculation.',
      quoteRefreshing: 'Refreshing quote...',
      refreshButton: 'Refresh quote',
      quantityInputLabel: 'Quantity',
      quantityHintsPrefix: 'Constraints',
      quantityHintAvailable: 'available',
      quantityHintMin: 'min',
      quantityHintMax: 'max',
      quantityHintStep: 'step',
      totalLabel: 'Total',
      unitPriceLabel: 'Unit price',
      unavailable:
        'Offer is currently unavailable. Close this modal and choose another offer.',
      priceChanged:
        'Price changed after the currency rate update. Review the updated total.',
      offerUpdated:
        'Offer updated. Review the new terms before creating the order.',
      submitPending: 'Creating order...',
      submitReady: 'Review quantity and create the order.',
      submitExpired: 'Quote expired. Wait for refresh.',
      invalidQuantity: 'Enter a valid quantity.',
      positiveQuantity: 'Quantity must be greater than zero.',
      minQuantity: 'Quantity must be at least {value}.',
      maxQuantity: 'Quantity must be at most {value}.',
      availableQuantity: 'Quantity cannot exceed available amount ({value}).',
      stepQuantity: 'Quantity must respect step {value}.',
      loading: 'Loading offer details...',
      error: "Couldn't load offer details.",
    },
    errors: {
      games: "Couldn't load games.",
      currencies: "Couldn't load currencies.",
      categories: "Couldn't load categories for the selected game.",
      schema: "Couldn't load market schema.",
      offers: "Couldn't load market offers.",
      offerDetails: "Couldn't load offer details.",
      quoteCreate: "Couldn't create an offer quote.",
      quoteRefresh: "Couldn't refresh the quote.",
      orderCreate: "Couldn't create the order.",
      currencyUnsupported:
        '{code} is not available for the current market. Showing prices in {fallback}.',
    },
  },
}

export function getMarketCopy(language = 'ru') {
  return MARKET_MESSAGES[language] || MARKET_MESSAGES.en
}
