const MARKET_MESSAGES = {
  ru: {
    eyebrow: 'Публичный рынок',
    title: 'Рынок валюты',
    subtitle:
      'Read-only витрина публичных валютных офферов. Переключайте сценарий покупки и продажи, сужайте контекст и просматривайте детали без создания ордера.',
    unsupportedCategoryTitle: 'Пока только currency',
    unsupportedCategoryText:
      'На этом этапе публичная market page поддерживает только категорию currency для выбранной игры.',
    common: {
      loading: 'Загрузка...',
      retry: 'Повторить',
      reset: 'Сбросить фильтры',
      noValue: 'Не указано',
      fallbackTitle: 'Валютный оффер',
      close: 'Закрыть',
      results: 'офферов',
      page: 'Страница',
      of: 'из',
      allGames: 'Игры недоступны',
      noCategories: 'Категории недоступны',
      filtersPending: 'Подгружаем рыночные фильтры...',
      filtersUnavailable: 'Сначала завершите настройку фильтров выше, затем список офферов станет доступен.',
      orderFlowNext: 'Создание ордера будет добавлено на следующем этапе.',
      comingSoon: 'Позже',
    },
    toolbar: {
      intent: 'Сценарий',
      game: 'Игра',
      category: 'Категория',
      viewerCurrency: 'Валюта просмотра',
      sort: 'Сортировка',
      contexts: 'Торговый контекст',
      keyAttribute: 'Тип валюты',
      categoriesLoading: 'Загружаем категории...',
      schemaLoading: 'Загружаем схему...',
    },
    intent: {
      buy: 'Купить',
      sell: 'Продать',
    },
    side: {
      buy: 'Покупатель',
      sell: 'Продавец',
    },
    actions: {
      buy: 'Купить',
      sell: 'Продать',
    },
    sort: {
      price_asc: 'Сначала лучшая цена',
      price_desc: 'Сначала высокая цена',
    },
    list: {
      title: 'Актуальные предложения',
      subtitle: 'Публичные офферы для выбранного рыночного сценария.',
      columns: {
        offer: 'Оффер',
        price: 'Цена',
        trade: 'Лимиты',
        action: 'Действие',
      },
      owner: 'Трейдер',
      quantity: 'Количество',
      limits: 'Лимиты',
      step: 'Шаг',
      context: 'Контекст',
      delivery: 'Передача',
      published: 'Опубликован',
      rate: 'Курс',
      loadingRefresh: 'Обновляем предложения...',
      noOffersTitle: 'Офферы не найдены',
      noOffersText:
        'Попробуйте другой сценарий, тип валюты или комбинацию контекстов, чтобы найти публичные предложения.',
      errorTitle: 'Не удалось загрузить рыночные офферы.',
      previous: 'Назад',
      next: 'Далее',
      showing: 'Показано',
    },
    modal: {
      title: 'Детали оффера',
      descriptionFallback: 'Описание не указано.',
      tradeTermsFallback: 'Дополнительные условия не указаны.',
      sectionContext: 'Контекст сделки',
      sectionAttributes: 'Атрибуты',
      sectionDelivery: 'Способы передачи',
      sectionDescription: 'Описание',
      sectionTerms: 'Условия сделки',
      quantity: 'Доступное количество',
      minTradeQuantity: 'Минимум за сделку',
      maxTradeQuantity: 'Максимум за сделку',
      quantityStep: 'Шаг количества',
      publishedAt: 'Опубликован',
      loading: 'Загружаем детали оффера...',
      error: 'Не удалось загрузить детали оффера.',
      primaryDisabledHint: 'Создание ордера на этом шаге ещё не реализовано.',
    },
    errors: {
      games: 'Не удалось загрузить игры.',
      categories: 'Не удалось загрузить категории для выбранной игры.',
      schema: 'Не удалось загрузить market schema.',
      offers: 'Не удалось загрузить рыночные офферы.',
      offerDetails: 'Не удалось загрузить детали оффера.',
    },
  },
  en: {
    eyebrow: 'Public market',
    title: 'Currency market',
    subtitle:
      'Read-only storefront for public currency offers. Switch intent, narrow the context, and inspect offers without creating orders.',
    unsupportedCategoryTitle: 'Currency only for now',
    unsupportedCategoryText:
      'This public market page currently supports only the currency category for the selected game.',
    common: {
      loading: 'Loading...',
      retry: 'Retry',
      reset: 'Reset filters',
      noValue: 'Not specified',
      fallbackTitle: 'Currency offer',
      close: 'Close',
      results: 'offers',
      page: 'Page',
      of: 'of',
      allGames: 'No games available',
      noCategories: 'No categories available',
      filtersPending: 'Loading market filters...',
      filtersUnavailable: 'Resolve the filter setup above to continue browsing offers.',
      orderFlowNext: 'Order creation comes in the next step.',
      comingSoon: 'Coming next step',
    },
    toolbar: {
      intent: 'Intent',
      game: 'Game',
      category: 'Category',
      viewerCurrency: 'Viewer currency',
      sort: 'Sort',
      contexts: 'Trade context',
      keyAttribute: 'Currency type',
      categoriesLoading: 'Loading categories...',
      schemaLoading: 'Loading schema...',
    },
    intent: {
      buy: 'Buy',
      sell: 'Sell',
    },
    side: {
      buy: 'Buyer',
      sell: 'Seller',
    },
    actions: {
      buy: 'Buy',
      sell: 'Sell',
    },
    sort: {
      price_asc: 'Best price first',
      price_desc: 'Highest price first',
    },
    list: {
      title: 'Live offers',
      subtitle: 'Public offers for the selected market view.',
      columns: {
        offer: 'Offer',
        price: 'Price',
        trade: 'Trade limits',
        action: 'Action',
      },
      owner: 'Trader',
      quantity: 'Quantity',
      limits: 'Limits',
      step: 'Step',
      context: 'Context',
      delivery: 'Delivery',
      published: 'Published',
      rate: 'Rate',
      loadingRefresh: 'Refreshing offers...',
      noOffersTitle: 'No offers found',
      noOffersText:
        'Try another intent, currency type, or context combination to surface public offers.',
      errorTitle: "Couldn't load market offers.",
      previous: 'Previous',
      next: 'Next',
      showing: 'Showing',
    },
    modal: {
      title: 'Offer details',
      descriptionFallback: 'No description provided.',
      tradeTermsFallback: 'No special trade terms provided.',
      sectionContext: 'Trade context',
      sectionAttributes: 'Attributes',
      sectionDelivery: 'Delivery methods',
      sectionDescription: 'Description',
      sectionTerms: 'Trade terms',
      quantity: 'Available quantity',
      minTradeQuantity: 'Minimum trade',
      maxTradeQuantity: 'Maximum trade',
      quantityStep: 'Quantity step',
      publishedAt: 'Published',
      loading: 'Loading offer details...',
      error: "Couldn't load offer details.",
      primaryDisabledHint: 'Order creation is not implemented on this step.',
    },
    errors: {
      games: "Couldn't load games.",
      categories: "Couldn't load categories for the selected game.",
      schema: "Couldn't load market schema.",
      offers: "Couldn't load market offers.",
      offerDetails: "Couldn't load offer details.",
    },
  },
}

export function getMarketCopy(language = 'ru') {
  return MARKET_MESSAGES[language] || MARKET_MESSAGES.en
}
