const OFFER_MESSAGES = {
  ru: {
    navLabel: 'Мои офферы',
    common: {
      loading: 'Загрузка...',
      retry: 'Повторить',
      backToList: 'Назад к офферам',
      changeResetHint: 'При смене игры или категории параметры контекста будут пересчитаны.',
      noValue: 'Не указано',
      yes: 'Да',
      no: 'Нет',
      selected: 'Выбрано',
      available: 'Доступно',
      optional: 'Необязательно',
      currentStatus: 'Текущий статус',
      afterSubmit: 'После отправки',
      notCreatedYet: 'Ещё не создан',
      unsavedChanges: 'Есть несохранённые изменения',
      noUnsavedChanges: 'Изменений пока нет',
      publishFromList: 'Статус публикации можно менять прямо из списка офферов.',
      createPublishesActive:
        'Оффер будет опубликован сразу после создания и появится в разделе моих офферов.',
      schemaPending: 'Сначала выберите игру и категорию, затем мы подгрузим точную схему оффера.',
      schemaEmpty: 'Для этой категории нет дополнительных контекстов или параметров.',
      schemaError: 'Не удалось загрузить схему оффера.',
      gamesError: 'Не удалось загрузить список игр.',
      categoriesError: 'Не удалось загрузить категории для выбранной игры.',
      listError: 'Не удалось загрузить список офферов.',
      loadOfferError: 'Не удалось загрузить оффер.',
      createError: 'Не удалось создать оффер.',
      saveError: 'Не удалось сохранить изменения.',
      publishError: 'Не удалось обновить статус оффера.',
      createSuccess: 'Оффер создан и опубликован.',
      saveSuccess: 'Изменения сохранены.',
      publishSuccess: 'Оффер опубликован.',
      pauseSuccess: 'Оффер снят с публикации.',
      fallbackTitle: 'Оффер без названия',
      untitledSuffix: 'Без названия',
    },
    list: {
      title: 'Мои офферы',
      subtitle:
        'Управляйте ассортиментом, обновляйте условия и быстро переключайте публикацию без перезагрузки страницы.',
      createCta: 'Создать новый оффер',
      emptyTitle: 'Офферов пока нет',
      emptySubtitle:
        'Создайте первое предложение, чтобы показать ассортимент покупателям и быстро вернуться к редактированию из личного кабинета.',
      emptyCta: 'Создать первый оффер',
      columns: {
        offer: 'Оффер',
        price: 'Цена и объём',
        status: 'Статус',
        actions: 'Действия',
      },
      quantityLabel: 'Количество',
      publishedAt: 'Опубликован',
      createdAt: 'Создан',
      edit: 'Редактировать',
      publish: 'Опубликовать',
      pause: 'Снять с публикации',
      updating: 'Обновляем...',
      noAction: 'Без действий',
    },
    form: {
      createTitle: 'Создать оффер',
      createSubtitle:
        'Соберите карточку предложения по шагам: сначала базовая информация, затем торговый контекст, параметры товара и условия сделки.',
      editTitle: 'Редактировать оффер',
      editSubtitle:
        'Обновите только нужные поля. При сохранении отправим аккуратный PATCH, чтобы не потерять различие между omitted, null и [].',
      overviewTitle: 'Сводка оффера',
      overviewSubtitle:
        'Проверьте основные параметры перед публикацией и сохранением изменений.',
      sections: {
        main: '1. Основное',
        context: '2. Контекст торговли',
        attributes: '3. Параметры товара',
        trade: '4. Условия сделки',
        publication: '5. Публикация',
      },
      sectionDescriptions: {
        main:
          'Выберите игру, категорию, сторону сделки и задайте понятное позиционирование оффера.',
        context:
          'Контекст помогает покупателю сразу понять платформу, лигу и другие условия торговли.',
        attributes:
          'Подберите товарные параметры по схеме категории. Это влияет на точность поиска и карточки оффера.',
        trade:
          'Укажите объём, шаг сделки, способы передачи и дополнительные договорённости.',
        publication:
          'На этом шаге мы фиксируем итог перед публикацией или сохранением изменений.',
      },
      fields: {
        game: 'Игра',
        category: 'Категория',
        side: 'Тип сделки',
        title: 'Заголовок',
        description: 'Описание',
        priceAmount: 'Цена',
        priceCurrencyCode: 'Валюта',
        quantity: 'Количество',
        minTradeQuantity: 'Минимум за сделку',
        maxTradeQuantity: 'Максимум за сделку',
        quantityStep: 'Шаг количества',
        tradeTerms: 'Условия сделки',
        deliveryMethods: 'Способы передачи',
      },
      helpers: {
        title:
          'Можно оставить пустым, если хотите использовать аккуратный автогенерируемый заголовок в списке.',
        description:
          'Коротко объясните, что вы предлагаете, и почему с вами удобно работать.',
        price: 'Цена за единицу товара или услуги.',
        priceCurrencyCode: 'Используйте стандартный код валюты, например USD, EUR или RUB.',
        tradeTerms:
          'Например: игровой ник, время ответа, формат контакта или нюансы передачи.',
        deliveryMethods:
          'Выберите один или несколько способов передачи. Покупателю это будет видно в карточке.',
      },
      keyAttributeLabel: 'Ключевой параметр',
      contextSummaryLabel: 'Контекст',
      deliverySummaryLabel: 'Передача',
      readinessLabel: 'Готовность',
      readyToPublish: 'Форма готова к публикации',
      selectGameAndCategory: 'Сначала выберите игру и категорию',
      fieldsLeft: (count) => `Осталось заполнить: ${count}`,
      deliverySummary: (count) => `Выбрано способов: ${count}`,
      actions: {
        create: 'Создать и опубликовать',
        save: 'Сохранить изменения',
        cancel: 'Отмена',
      },
      validation: {
        gameRequired: 'Выберите игру.',
        categoryRequired: 'Выберите категорию.',
        sideRequired: 'Выберите тип сделки.',
        priceAmountRequired: 'Укажите цену.',
        priceAmountInvalid: 'Введите корректную цену больше нуля.',
        currencyRequired: 'Укажите код валюты.',
        numericRequired: 'Заполните числовое поле.',
        numericInvalid: 'Введите корректное число больше нуля.',
        contextRequired: 'Выберите значение.',
        attributeRequired: 'Заполните поле.',
        multiselectRequired: 'Выберите хотя бы один вариант.',
        minMaxInvalid: 'Минимальное количество не может быть больше максимального.',
        maxQuantityInvalid: 'Максимум за сделку не должен превышать общее количество.',
        minQuantityInvalid: 'Минимум за сделку не должен превышать общее количество.',
        noChanges: 'Изменений нет. Обновите хотя бы одно поле перед сохранением.',
      },
      draftLabel: 'Черновик формы',
      createHint: 'Мы создадим оффер со статусом Active.',
      editHint: 'Поля без изменений не попадут в PATCH.',
      createPublicationLabel: 'Режим публикации',
      createPublicationHelper: 'Оффер будет опубликован сразу после создания.',
      createSummaryStatusLabel: 'Будет опубликован как',
      retryOffer: 'Загрузить оффер ещё раз',
    },
    side: {
      buy: 'Покупка',
      sell: 'Продажа',
    },
    status: {
      active: 'Активен',
      paused: 'На паузе',
      draft: 'Черновик',
      closed: 'Закрыт',
      unknown: 'Без статуса',
    },
  },
  en: {
    navLabel: 'My offers',
    common: {
      loading: 'Loading...',
      retry: 'Retry',
      backToList: 'Back to offers',
      changeResetHint:
        'Changing the game or category recalculates context-specific parameters.',
      noValue: 'Not specified',
      yes: 'Yes',
      no: 'No',
      selected: 'Selected',
      available: 'Available',
      optional: 'Optional',
      currentStatus: 'Current status',
      afterSubmit: 'After submit',
      notCreatedYet: 'Not created yet',
      unsavedChanges: 'Unsaved changes',
      noUnsavedChanges: 'No changes yet',
      publishFromList: 'Use the offers list to change publication status.',
      createPublishesActive:
        'The offer will be published immediately after creation and appear in your offers list.',
      schemaPending: 'Select a game and category first to load the exact offer schema.',
      schemaEmpty: 'This category has no extra contexts or item parameters.',
      schemaError: "Couldn't load the offer schema.",
      gamesError: "Couldn't load the games list.",
      categoriesError: "Couldn't load categories for the selected game.",
      listError: "Couldn't load offers.",
      loadOfferError: "Couldn't load the offer.",
      createError: "Couldn't create the offer.",
      saveError: "Couldn't save changes.",
      publishError: "Couldn't update the offer status.",
      createSuccess: 'Offer created and published.',
      saveSuccess: 'Changes saved.',
      publishSuccess: 'Offer published.',
      pauseSuccess: 'Offer unpublished.',
      fallbackTitle: 'Untitled offer',
      untitledSuffix: 'Untitled',
    },
    list: {
      title: 'My offers',
      subtitle:
        'Manage your catalog, update trade terms, and toggle publication without a full page reload.',
      createCta: 'Create a new offer',
      emptyTitle: 'No offers yet',
      emptySubtitle:
        'Create your first listing to put inventory on the marketplace and come back to edit it from the dashboard.',
      emptyCta: 'Create first offer',
      columns: {
        offer: 'Offer',
        price: 'Price and volume',
        status: 'Status',
        actions: 'Actions',
      },
      quantityLabel: 'Quantity',
      publishedAt: 'Published',
      createdAt: 'Created',
      edit: 'Edit',
      publish: 'Publish',
      pause: 'Unpublish',
      updating: 'Updating...',
      noAction: 'No actions',
    },
    form: {
      createTitle: 'Create offer',
      createSubtitle:
        'Build the offer step by step: base info first, then trade context, product attributes, and transaction terms.',
      editTitle: 'Edit offer',
      editSubtitle:
        'Update only what matters. On save we build a careful PATCH payload that preserves omitted, null, and [].',
      overviewTitle: 'Offer summary',
      overviewSubtitle: 'Review the key parameters before publishing or saving changes.',
      sections: {
        main: '1. Basics',
        context: '2. Trade context',
        attributes: '3. Product attributes',
        trade: '4. Deal terms',
        publication: '5. Publication',
      },
      sectionDescriptions: {
        main:
          'Choose the game, category, trade side, and define a clear positioning for the offer.',
        context:
          'Trade context helps buyers understand platform, league, and other conditions at a glance.',
        attributes:
          'Fill product attributes from the category schema to improve search precision and offer clarity.',
        trade:
          'Define amount, deal step, delivery methods, and additional instructions for the trade.',
        publication:
          'We lock the final state here before publishing or saving the edited offer.',
      },
      fields: {
        game: 'Game',
        category: 'Category',
        side: 'Trade side',
        title: 'Title',
        description: 'Description',
        priceAmount: 'Price',
        priceCurrencyCode: 'Currency',
        quantity: 'Quantity',
        minTradeQuantity: 'Minimum per deal',
        maxTradeQuantity: 'Maximum per deal',
        quantityStep: 'Quantity step',
        tradeTerms: 'Trade terms',
        deliveryMethods: 'Delivery methods',
      },
      helpers: {
        title:
          'You can keep it empty if you prefer a generated fallback title in the list view.',
        description:
          'Briefly explain what you offer and why the trade with you is straightforward.',
        price: 'Price per item or service unit.',
        priceCurrencyCode: 'Use a standard currency code such as USD, EUR, or RUB.',
        tradeTerms:
          'For example: in-game nickname, response time, contact format, or handoff details.',
        deliveryMethods:
          'Select one or more delivery options. Buyers will see them in the offer card.',
      },
      keyAttributeLabel: 'Key attribute',
      contextSummaryLabel: 'Context',
      deliverySummaryLabel: 'Delivery',
      readinessLabel: 'Readiness',
      readyToPublish: 'Ready to publish',
      selectGameAndCategory: 'Select a game and category first',
      fieldsLeft: (count) => `${count} fields left`,
      deliverySummary: (count) => `${count} methods selected`,
      actions: {
        create: 'Create and publish',
        save: 'Save changes',
        cancel: 'Cancel',
      },
      validation: {
        gameRequired: 'Select a game.',
        categoryRequired: 'Select a category.',
        sideRequired: 'Select a trade side.',
        priceAmountRequired: 'Enter a price.',
        priceAmountInvalid: 'Enter a valid price greater than zero.',
        currencyRequired: 'Enter a currency code.',
        numericRequired: 'Fill in the numeric field.',
        numericInvalid: 'Enter a valid number greater than zero.',
        contextRequired: 'Choose a value.',
        attributeRequired: 'Fill in the field.',
        multiselectRequired: 'Select at least one option.',
        minMaxInvalid: 'Minimum per deal cannot exceed maximum per deal.',
        maxQuantityInvalid: 'Maximum per deal cannot exceed total quantity.',
        minQuantityInvalid: 'Minimum per deal cannot exceed total quantity.',
        noChanges: 'No changes detected. Update at least one field before saving.',
      },
      draftLabel: 'Form draft',
      createHint: 'We will create the offer with Active status.',
      editHint: 'Unchanged fields stay out of the PATCH request.',
      createPublicationLabel: 'Publication mode',
      createPublicationHelper: 'The offer will be published immediately after creation.',
      createSummaryStatusLabel: 'Will be published as',
      retryOffer: 'Load the offer again',
    },
    side: {
      buy: 'Buy',
      sell: 'Sell',
    },
    status: {
      active: 'Active',
      paused: 'Paused',
      draft: 'Draft',
      closed: 'Closed',
      unknown: 'Unknown',
    },
  },
}

export function getOfferCopy(language = 'ru') {
  return OFFER_MESSAGES[language] || OFFER_MESSAGES.ru
}
